---
- name: Tomcat Deployment
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    URL_ART: "http://3.109.5.157:8081/repository/my-artifacts/com/springhow/example/helloworld/0.0.1/helloworld-0.0.1.war"
    URL_TOM: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.zip"
    URL_TOMZIP: "{{ URL_TOM.split('/') | last }}"
  tasks:
    - name: Download Artifact
      copy:
        src: ./simple-app-7.0.0.war
        dest: /opt/tomcat8/webapps/
    - name: start tomcat
      shell: sh /opt/tomcat8/bin/startup.sh start
